# Generated by Django 3.1.12 on 2024-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture-973460_640.png', upload_to='profile_images/'),
        ),
    ]
